teaching:
  sections:
    - education
    - teaching experience
    - research experience
    - publications
    - science communication
    - skills
    - awards, fellowships and grants
research:
  sections:
    - research experience
    - education
    - publications
    - conference talks
    - poster presentations
    - awards, fellowships and grants
    - skills
short:
  sections:
    - education
    - research experience
    - skills